name: bohurupi_order_cms
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4

  # State management
  provider: ^6.1.1

  # UI/UX Packages
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  animate_do: ^3.1.2

  # New dependencies
  pull_to_refresh: ^2.0.0
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.3.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  firebase_auth_web: ^5.8.13

flutter:
  uses-material-design: true

  # Add assets
  assets:
    - assets/
    - assets/icons/
    - assets/images/
